import { makeStyles } from "@mui/styles";

const useStyles = makeStyles({
  root: {
    position: "relative",
    width: "100%",
    // height: "70px",
    // backgroundColor: "#020120",
    // color: "red",
    top: 0,
    zIndex: 100,
    // boxShadow: `0px 0px 2px 2px aqua,
    //   0 4px 8px 0 rgba(10, 255, 182, 0.37), 0 6px 20px 0 rgba(0, 0, 0, 0.19)`,
    backgroundColor: "black",
    // background: "rgb(2,0,36)",
    backgroundRepeat: "no-repeat",
    height: "600px",
    backgroundPosition: "center center",
    backgroundSize: "100vw auto",
    overflow: "hidden",
  },
  headerContainer: {
    position: "fixed",
    top: "-25px",
    display: "flex",
    alignItems: "center",
    width: "95%",
    height: "70px",
    overflow: "hidden",
    justifyContent: "space-between",
    padding: "10px",
  },
  headerLeft: {
    display: "flex",
    padding: "0 15px",
    cursor: "pointer",
    // border: "solid white 2px",
    background: "aqua",
    borderRadius: "8px",
    height: "50px",
    marginTop: "40px",
    marginLeft: "40px",
  },
  headerTitle: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  muiSvgMovie: {
    color: "black",
    fontSize: "20px",
  },
  headerTitleH3: {
    fontSize: "2.1rem",
    fontWeight: 500,
    marginLeft: "10px",
    "@media(max-width:400px)": {
      fontSize: "1.1rem",
    },
  },
  headerRight: {
    display: "flex",
    padding: "5px",
    marginTop: "25px",
    alignItems: "center",
    border: "2px solid aqua",
    borderRadius: "5px",
    cursor: "pointer",
  },
  muiSvgCloud: {
    color: "aqua",
    fontSize: "2.1rem",
    marginRight: "5px",
    cursor: "pointer",
  },
  button: {
    padding: "2px",
    fontSize: "1.1rem",
    backgroundColor: "transparent",
    color: "white",
    outline: "none",
    border: "none",
    cursor: "pointer",
  },
  fadeBottom: {
    position: "absolute",
    bottom: 0,
    width: "100%",
    height: "150px",
    background:
      "linear-gradient(rgba(14,42,71,0.001),rgba(14,42,71,0.06),rgba(14,42,71,0.6), rgba(14,42,71,0.9), #0E2A47);",
  },
  leftContent: {
    position: "absolute",
    top: "280px",
    left: "100px",
    width: "450px",
    height: "150px",
    padding: "0 10px",
    background: "rgba(0,0,0,0.2)",
    color: "white",
    "@media (max-width : 1300px)": {
      // top: "180px",
      left: "10px",
      // width: "90%",
    },
    "@media (max-width : 1100px)": {
      width: "350px",
    },
    "@media (max-width : 600px)": {
      top: "180px",
      left: "10px",
      width: "90%",
    },
  },
  plot: {
    color: "#C6CBD1",
  },
  // innerLeftContent: {
  //   width: "100%",
  //   height: "100%",
  //   padding: "0px",
  //   margin: "0px",
  // },
});

export default useStyles;
